### PR TITLE
add yml file

### PR DESCRIPTION
**Pull request by samwaseda**

### CODE REVIEW

**Comment by samwaseda** [comment]
@liamhuber this one is failing for reasons that I don’t really understand. Could you maybe take a look?

**Comment by liamhuber** [comment]
I followed [the link in the error message](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/) and see that Mambaforge is getting sunsetted. `conda-incubator/setup-miniconda` takes a miniforge variant argument. We default this to "Mambaforge", but you can change it:

https://github.com/pyiron/actions/blob/72012de602e4dbe8c1e5efa1b0bd32e63427fd02/cached-miniforge/action.yml#L28-L31

Try changing the `miniforge-variant` argument to see if that fixes it. Probably we need to change the default upstream in `pyiron/actions/cached-miniforge` too -- if this solution works, would you do that?

**Comment by samwaseda** [comment]
How do I change it?

**Comment by liamhuber** [comment]
Just as a keyword argument in the workflow. Look at workflows or another repo for an example

**Comment by liamhuber** [comment]
1) mea culpa -- I was wrong, the reusable actions don't let you drill down so deep in the action arguments as to expose `pyiron/actions/cached-miniforge.miniforge-variant`. The `cached-miniforge` action is nicely exposing the `conda-incubator/setup-miniconda` options, I just didn't propagate it all the way do the reusable workflows (which are usable only internally to the pyiron org), nor do I want to bother

2) This just crashed all my daily tests too. I opened [a PR](https://github.com/pyiron/actions/pull/132) to change the default target, but [when I test it](https://github.com/pyiron/pyiron_workflow/pull/483), I'm fighting with 404 errors for URLs that look like they ought to resolve to me...

**Comment by liamhuber** [comment]
> I'm fighting with 404 errors for URLs that look like they ought to resolve to me...

Ok, I just had a typo 🤦‍♂️

**Pull request merged**
